/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controle.VendaCtrl;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.ClienteTabelaModelo;
import model.beans.Cliente;

/**
 *
 * @author jp
 */
public class jfBuscaClienteParaVenda extends javax.swing.JFrame
{
    private VendaCtrl vend;
    private ClienteTabelaModelo modeloDaTabela;

    /**
     * Creates new form BuscaClienteParaVenda
     */
    public jfBuscaClienteParaVenda(VendaCtrl vend)
    {
        initComponents();
        this.vend = vend;
        
        this.modeloDaTabela = new ClienteTabelaModelo();
        this.tabela.setModel(modeloDaTabela);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        selecionar = new javax.swing.JButton();

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        selecionar.setText("selecionar");
        selecionar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                selecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(selecionar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(selecionar)
                .addContainerGap(364, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selecionarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_selecionarActionPerformed
    {//GEN-HEADEREND:event_selecionarActionPerformed
        int[] linhas = this.tabela.getSelectedRows();
        if (linhas.length == 1)
        {
            this.vend.setClienteDaVenda(this.modeloDaTabela.getDados().get(linhas[0]));
            this.dispose();
        }
        
        else if (linhas.length == 0)
            JOptionPane.showMessageDialog(null, "Um cliente deve ser selecionado",
                        "Erro", JOptionPane.ERROR_MESSAGE);
        else
            JOptionPane.showMessageDialog(null, "Apenas um cliente deve ser selecionado",
                "Erro", JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_selecionarActionPerformed
    
    
    public void setTabelaDados(ArrayList<Cliente> cli)
    {
        this.modeloDaTabela.adicionaLinhas(cli);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton selecionar;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
