/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author EDUARDE
 */
public class JfPagamento extends javax.swing.JFrame {

    private int numParcelas;
    /**
     * Creates new form JifPagamento
     */
    public JfPagamento() {
        initComponents();
        jFormaPag.setEnabled(false);
        numParcelas = 1;
        jPagAvista.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoValor = new javax.swing.JTextField();
        jFormaPag = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPagAvista = new javax.swing.JRadioButton();
        jPagCartao = new javax.swing.JRadioButton();
        jPagCheque = new javax.swing.JRadioButton();
        confirma = new javax.swing.JButton();
        retornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("PAGAMENTO");

        jLabel1.setText("Valor Total:");

        jFormaPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 x", "2 x", "3 x", "4 x", "5 x" }));

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, jFormaPag, org.jdesktop.beansbinding.ELProperty.create("${selectedItem}"), jFormaPag, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        jFormaPag.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jFormaPagActionPerformed(evt);
            }
        });

        jLabel2.setText("Forma de Pagamento: ");

        jPagAvista.setText("À vista");
        jPagAvista.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jPagAvistaActionPerformed(evt);
            }
        });

        jPagCartao.setText("Parcelado Cartão");
        jPagCartao.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jPagCartaoActionPerformed(evt);
            }
        });

        jPagCheque.setText("Cheque");
        jPagCheque.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jPagChequeActionPerformed(evt);
            }
        });

        confirma.setText("Confirmar Pagamento");

        retornar.setText("Retornar");
        retornar.setToolTipText("Cancela a venda e retorna ao menu principal");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPagAvista, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jFormaPag, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPagCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(45, 45, 45)
                                .addComponent(jPagCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(confirma)
                        .addGap(52, 52, 52)
                        .addComponent(retornar))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(campoValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPagAvista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPagCartao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPagCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jFormaPag)
                .addGap(112, 112, 112)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(retornar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormaPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormaPagActionPerformed
        // para forma de pagamento parcelado
        
        String s = (String) jFormaPag.getSelectedItem();
        s = s.substring(0, 1);
        int a = Integer.parseInt(s);
        if (a < 1) a = 1;
        this.numParcelas = a;
        
    }//GEN-LAST:event_jFormaPagActionPerformed

    private void jPagAvistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPagAvistaActionPerformed
        // Ação de pagamento a vista
        jPagAvista.setEnabled(true);
        jPagCartao.setSelected(false);
        jPagCheque.setSelected(false);
        jFormaPag.setEnabled(false);
        numParcelas = 1;
      
        
    }//GEN-LAST:event_jPagAvistaActionPerformed

    private void jPagCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPagCartaoActionPerformed
        // ação de pagamento cartão
        jPagCartao.setEnabled(true);
        jPagCheque.setSelected(false);
        jPagAvista.setSelected(false);
        jFormaPag.setEnabled(true);
        
    }//GEN-LAST:event_jPagCartaoActionPerformed

    private void jPagChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPagChequeActionPerformed
        // ação de pagamento cheque
        jPagCheque.setSelected(true);
        jPagAvista.setSelected(false);
        jPagCartao.setSelected(false);
        jFormaPag.setEnabled(false);
        numParcelas = 1;
    }//GEN-LAST:event_jPagChequeActionPerformed
    
    
    public void adicionaOuvintes(ActionListener ouvinte)
    {
        this.confirma.addActionListener(ouvinte);
        this.retornar.addActionListener(ouvinte);
    }
    
    public void setValorTotal(double valor)
    {
        Double a = valor;
        this.campoValor.setText(a.toString());
        this.campoValor.setEditable(false);
    }
    
    public boolean isAvista()
    {
        return this.jPagAvista.isSelected();
    }
    
    public boolean isCheque()
    {
        return this.jPagCheque.isSelected();
    }
    
    public boolean isCartao()
    {
        return this.jPagCartao.isSelected();
    }
    
    public int getNumParcelas()
    {
        return this.numParcelas;
    }
        
    public JButton getConfirma()
    {
        return this.confirma;
    }
    
    public JButton getRetornar()
    {
        return this.retornar;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoValor;
    private javax.swing.JButton confirma;
    private javax.swing.JComboBox<String> jFormaPag;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jPagAvista;
    private javax.swing.JRadioButton jPagCartao;
    private javax.swing.JRadioButton jPagCheque;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton retornar;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
