/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.ProdutoTabelaModelo;
import model.beans.Produto;

/**
 *
 * @author EDUARDE
 */
public class jfVendas extends javax.swing.JFrame {

    private principal telaPrincipal;
    private ProdutoTabelaModelo modeloDaTabela;
    private double precoTotal;
    
    /**
     * Creates new form jfVendas
     */
    public jfVendas(principal telaPrincipal) {
        initComponents();
        this.telaPrincipal = telaPrincipal;
        
        this.modeloDaTabela = new ProdutoTabelaModelo();
        this.tabela.setModel(modeloDaTabela);
        
        this.precoTotal = 0;
        this.modeloDaTabela.setHabEdicao(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        nomeCliente = new javax.swing.JTextField();
        buscarCli = new javax.swing.JButton();
        confirmaVenda = new javax.swing.JButton();
        jVendasCancela = new javax.swing.JButton();
        cpfCliente = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        cliAnonimo = new javax.swing.JCheckBox();
        valorTotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        info = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        campoPesquisaProd = new javax.swing.JTextField();
        pesquisarProd = new javax.swing.JButton();
        deletarProd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENDAS");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                fechar(evt);
            }
        });

        jLabel1.setText("Nome Cliente:");

        buscarCli.setText("Carregar Dados");

        confirmaVenda.setText("Confima Venda");
        confirmaVenda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                confirmaVendaActionPerformed(evt);
            }
        });

        jVendasCancela.setText("Cancelar Operação");
        jVendasCancela.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jVendasCancelaActionPerformed(evt);
            }
        });

        try
        {
            cpfCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex)
        {
            ex.printStackTrace();
        }
        cpfCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cpfClienteActionPerformed(evt);
            }
        });

        jLabel2.setText("CPF:");

        cliAnonimo.setText("Cliente não cadastrado");

        valorTotal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                valorTotalActionPerformed(evt);
            }
        });

        jLabel3.setText("Total:");

        info.setColumns(20);
        info.setRows(5);
        jScrollPane2.setViewportView(info);

        jLabel4.setText("Cod Produto:");

        pesquisarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Buscar.png"))); // NOI18N
        pesquisarProd.setText("Pesquisar");

        deletarProd.setText("Deletar produto");

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jVendasCancela)
                                    .addGap(48, 48, 48)
                                    .addComponent(confirmaVenda)))
                            .addComponent(deletarProd)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoPesquisaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pesquisarProd))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cliAnonimo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(34, 34, 34)
                                        .addComponent(buscarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(buscarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cliAnonimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoPesquisaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(pesquisarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(deletarProd)
                                .addGap(79, 79, 79)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmaVenda)
                            .addComponent(jVendasCancela)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        setBounds(0, 0, 991, 736);
    }// </editor-fold>//GEN-END:initComponents

    private void confirmaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmaVendaActionPerformed
       
    }//GEN-LAST:event_confirmaVendaActionPerformed

    private void cpfClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfClienteActionPerformed

    }//GEN-LAST:event_cpfClienteActionPerformed

    private void valorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorTotalActionPerformed

    }//GEN-LAST:event_valorTotalActionPerformed

    private void jVendasCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVendasCancelaActionPerformed

        int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente cancelar a venda?");
        if(resposta != 0)
            return;
        this.telaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jVendasCancelaActionPerformed

    private void fechar(java.awt.event.WindowEvent evt)//GEN-FIRST:event_fechar
    {//GEN-HEADEREND:event_fechar
        int resposta = JOptionPane.showConfirmDialog(this, "Deseja realmente cancelar a venda?");
        if(resposta != 0)
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        else
        {
            this.telaPrincipal.setVisible(true);
            this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }
    }//GEN-LAST:event_fechar

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_tabelaMouseClicked
    {//GEN-HEADEREND:event_tabelaMouseClicked
        if (this.modeloDaTabela.foiEditado())
            this.atualizaTotal();
        
    }//GEN-LAST:event_tabelaMouseClicked

    public void adicionaOuvinte(ActionListener ouvinte)
    {
        this.buscarCli.addActionListener(ouvinte);
        this.pesquisarProd.addActionListener(ouvinte);
        this.deletarProd.addActionListener(ouvinte);
        this.confirmaVenda.addActionListener(ouvinte);
    }
    
    public ProdutoTabelaModelo getModeloDaTabela()
    {
        return this.modeloDaTabela;
    }
    
    public JTable getTabela()
    {
        return this.tabela;
    }
    
    public void setTabelaDado(Produto p)
    {
        p.setQtd(1);
        this.modeloDaTabela.adicionaLinha(p);
        this.precoTotal += (p.getValorVenda() * p.getQtd());
        Double a = this.precoTotal;
        this.valorTotal.setText(a.toString());
    }
    
    public void atualizaTotal()
    {
        this.precoTotal = 0;
        ArrayList<Produto> v = this.modeloDaTabela.getDados();
        for (Produto p : v)
            this.precoTotal += (p.getQtd() * p.getValorVenda());
        
        Double a = this.precoTotal;
        this.valorTotal.setText(a.toString());
        this.modeloDaTabela.setFoiEditado(false);
    }
    
    public void fechaVenda()
    {
        this.telaPrincipal.setVisible(true);
        this.dispose();
    }

    public double getPrecoTotal()
    {
        return precoTotal;
    }

    public void setPrecoTotal(double precoTotal)
    {
        this.precoTotal = precoTotal;
    }
    
    public JButton getPesquisarProd()
    {
        return this.pesquisarProd;
    }
    
    public JButton getBuscarCli()
    {
        return this.buscarCli;
    }
    
    public JButton getDeletarProd()
    {
        return this.deletarProd;
    }
    
    public JButton getConfirmaVenda()
    {
        return this.confirmaVenda;
    }
    
    public boolean getCliAnonimo()
    {
        return this.cliAnonimo.isSelected();
    }
    
    public void addInfo(String str)
    {
        this.info.append(str);
    }
    
    public String getNomeCliente()
    {
        if (this.nomeCliente.getText().equals("")) return null;
        return this.nomeCliente.getText();
    }
    
    public String getCampoPesquisaProd()
    {
        return this.campoPesquisaProd.getText();
    }
    
    public String getCpfCliente()
    {
        if (this.cpfCliente.getText().charAt(0) == ' ') return null;
        return this.cpfCliente.getText();
    }
    
    public javax.swing.JDesktopPane getDesktop()
    {
        return this.jDesktopPane1;
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(jfVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(jfVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(jfVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(jfVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new jfVendas().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarCli;
    private javax.swing.JTextField campoPesquisaProd;
    private javax.swing.JCheckBox cliAnonimo;
    private javax.swing.JButton confirmaVenda;
    private javax.swing.JFormattedTextField cpfCliente;
    private javax.swing.JButton deletarProd;
    private javax.swing.JTextArea info;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jVendasCancela;
    private javax.swing.JTextField nomeCliente;
    private javax.swing.JButton pesquisarProd;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField valorTotal;
    // End of variables declaration//GEN-END:variables
}
