/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controle.ClienteCtrl;
import controle.ColaboradorCtrl;
import controle.ProdutoCtrl;
import controle.VendaCtrl;
import controle.VendasPorDiaCtrl;
import model.beans.Colaborador;

/**
 *
 * @author EDUARDE DAVID FREITAS BRANDÃO
 *         OSEIAS AYRES FERREIRA
 *         JOÃO PAULO NESPOLO
 */
public class principal extends javax.swing.JFrame {
    
    private Colaborador funcionarioLogado;

    /**
     * Creates new form principal
     */
    public principal(Colaborador c) {
        initComponents();
        this.funcionarioLogado = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jdpprincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jCadastro = new javax.swing.JMenu();
        jCadastroClientes = new javax.swing.JMenuItem();
        jCadastroFuncionarios = new javax.swing.JMenuItem();
        jCadastroProdutos = new javax.swing.JMenuItem();
        jVendas = new javax.swing.JMenu();
        jGerarVenda = new javax.swing.JMenuItem();
        jRelatorios = new javax.swing.JMenu();
        jRelatorioClientes = new javax.swing.JMenuItem();
        jRelatorioVendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpprincipalLayout = new javax.swing.GroupLayout(jdpprincipal);
        jdpprincipal.setLayout(jdpprincipalLayout);
        jdpprincipalLayout.setHorizontalGroup(
            jdpprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 861, Short.MAX_VALUE)
        );
        jdpprincipalLayout.setVerticalGroup(
            jdpprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 255));
        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jCadastro.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCadastro.setText("Cadastro");
        jCadastro.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N

        jCadastroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/User.png"))); // NOI18N
        jCadastroClientes.setText("Clientes");
        jCadastroClientes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCadastroClientesActionPerformed(evt);
            }
        });
        jCadastro.add(jCadastroClientes);

        jCadastroFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Usuario.png"))); // NOI18N
        jCadastroFuncionarios.setText("Funcionarios");
        jCadastroFuncionarios.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCadastroFuncionariosActionPerformed(evt);
            }
        });
        jCadastro.add(jCadastroFuncionarios);

        jCadastroProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Novo.png"))); // NOI18N
        jCadastroProdutos.setText("Produtos");
        jCadastroProdutos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCadastroProdutosActionPerformed(evt);
            }
        });
        jCadastro.add(jCadastroProdutos);

        jMenuBar1.add(jCadastro);

        jVendas.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, java.awt.Color.gray));
        jVendas.setText("Vendas");
        jVendas.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jVendas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jVendasActionPerformed(evt);
            }
        });

        jGerarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_carrinho_add.png"))); // NOI18N
        jGerarVenda.setText("Gerar uma venda");
        jGerarVenda.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jGerarVendaActionPerformed(evt);
            }
        });
        jVendas.add(jGerarVenda);

        jMenuBar1.add(jVendas);

        jRelatorios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jRelatorios.setText("Relatorios");
        jRelatorios.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N

        jRelatorioClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BuscarFunc.png"))); // NOI18N
        jRelatorioClientes.setText("Clientes");
        jRelatorioClientes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRelatorioClientesActionPerformed(evt);
            }
        });
        jRelatorios.add(jRelatorioClientes);

        jRelatorioVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon_carrinho_add.png"))); // NOI18N
        jRelatorioVendas.setText("Vendas / Dia");
        jRelatorioVendas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRelatorioVendasActionPerformed(evt);
            }
        });
        jRelatorios.add(jRelatorioVendas);

        jMenuBar1.add(jRelatorios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpprincipal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jdpprincipal)
                .addContainerGap())
        );

        setBounds(0, 0, 895, 616);
    }// </editor-fold>//GEN-END:initComponents

    private void jCadastroFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroFuncionariosActionPerformed
        // cria a tela de cadastro de funcionarios
        JifCadastroFuncionarios obj = new JifCadastroFuncionarios(); 
        jdpprincipal.add(obj);
        obj.setVisible(true);
        
        ColaboradorCtrl controle = new ColaboradorCtrl(obj);
    }//GEN-LAST:event_jCadastroFuncionariosActionPerformed

    private void jCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroClientesActionPerformed
        // cria a tela de cadastro de clientes
        jifCadastroCliente tela = new jifCadastroCliente();
        jdpprincipal.add(tela);
        tela.setVisible(true);       
        
        ClienteCtrl controle = new ClienteCtrl(tela);
    }//GEN-LAST:event_jCadastroClientesActionPerformed

    
    
    private void jGerarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGerarVendaActionPerformed
        // local onde vai chamar a tela de vendas
        jfVendas tela = new jfVendas(this);
        tela.setVisible(true);
        this.setVisible(false);
        
        VendaCtrl controle = new VendaCtrl(tela, this.funcionarioLogado);
    }//GEN-LAST:event_jGerarVendaActionPerformed

    private void jRelatorioClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelatorioClientesActionPerformed
        // local onde vai instanciar a tela do relatorio de clientes
        jfBuscaCliente tela = new jfBuscaCliente(this);
        tela.setVisible(true);
        this.setVisible(false);
        
        ClienteCtrl controle = new ClienteCtrl(tela);
    }//GEN-LAST:event_jRelatorioClientesActionPerformed

    private void jVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jVendasActionPerformed

    private void jCadastroProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroProdutosActionPerformed
        // chamada para instanciar a tela de cadastro de produtos
        JifCadastrodeProduto tela = new JifCadastrodeProduto();
        jdpprincipal.add(tela);
        tela.setVisible(true);
        
        ProdutoCtrl controle = new ProdutoCtrl(tela);
    }//GEN-LAST:event_jCadastroProdutosActionPerformed

    private void jRelatorioVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelatorioVendasActionPerformed
        JfVendasPorDia tela = new JfVendasPorDia(this);
        tela.setVisible(true);
        this.setVisible(false);
        
        VendasPorDiaCtrl controle = new VendasPorDiaCtrl(tela);
    }//GEN-LAST:event_jRelatorioVendasActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new principal().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jCadastro;
    private javax.swing.JMenuItem jCadastroClientes;
    private javax.swing.JMenuItem jCadastroFuncionarios;
    private javax.swing.JMenuItem jCadastroProdutos;
    private javax.swing.JMenuItem jGerarVenda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jRelatorioClientes;
    private javax.swing.JMenuItem jRelatorioVendas;
    private javax.swing.JMenu jRelatorios;
    private javax.swing.JMenu jVendas;
    public javax.swing.JDesktopPane jdpprincipal;
    // End of variables declaration//GEN-END:variables
}
